########################################################################
#
# Makefile
# Makefile für LaTeX
#
########################################################################

TARGET=document.pdf
LL=latexmk -pdf
CLEAN=latexmk -c

all: contributors.tex revision.tex $(TARGET)
pdf: contributors.tex revision.tex $(TARGET)
.PHONY : clean contributors.tex revision.tex $(TARGET)

$(TARGET): $(TARGET:%.pdf=%.tex) contributors.tex revision.tex
	$(LL) $<

clean:
	$(CLEAN)
	rm -f revision.tex
	rm -f contributors.tex

contributors.tex:
	echo "% Autogenerated by Makefile, do not edit" > contributors.tex
	sed 's/$$/\\\\/g' CONTRIBUTORS >> contributors.tex

revision.tex:
	echo "% Autogenerated by Makefile, do not edit" > revision.tex
	echo "\\newcommand{\\REVISIONDATE}{`git log -1 --format=\"%ad\" --date=short`}" >> revision.tex
	echo "\\newcommand{\\REVISION}{`git log -1 --format=\"%h\"`}" >> revision.tex

# EOF
